apiVersion: v1
kind: Service
metadata:
  name: alert-service
  labels:
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/component: api
    monitoring: aware
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /actuator/prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alert-service
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
